### PR TITLE
add keystone v3 support + new click argument

### PR DESCRIPTION
**Pull request by patchkez**

### CODE REVIEW

**Comment by patchkez** [comment]
@eduardocerqueira can you please review and merge if the changes looks ok to you? I tried janitor script in upshift environment and it worked fine.

**Comment by patchkez** [comment]
@eduardocerqueira did you have chance to review my PR?

**Comment by patchkez** [comment]
@eduardocerqueira please review my PR

**Review by eduardocerqueira — APPROVED** [review]
looks good!

**Pull request merged**
